# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/junningfan/SSD_LITEON/UbuntuShared/4601/Vivado/baseDesign_stream/baseline_hls.srcs/sources_1/bd/design_4/ip/design_4_fir_stream_0_2/design_4_fir_stream_0_2.xci
# IP: The module: 'design_4_fir_stream_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/junningfan/SSD_LITEON/UbuntuShared/4601/Vivado/baseDesign_stream/baseline_hls.gen/sources_1/bd/design_4/ip/design_4_fir_stream_0_2/constraints/fir_stream_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_fir_stream_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /media/junningfan/SSD_LITEON/UbuntuShared/4601/Vivado/baseDesign_stream/baseline_hls.srcs/sources_1/bd/design_4/ip/design_4_fir_stream_0_2/design_4_fir_stream_0_2.xci
# IP: The module: 'design_4_fir_stream_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/junningfan/SSD_LITEON/UbuntuShared/4601/Vivado/baseDesign_stream/baseline_hls.gen/sources_1/bd/design_4/ip/design_4_fir_stream_0_2/constraints/fir_stream_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_fir_stream_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
