# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_4/design_4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4 || ORIG_REF_NAME==design_4} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axcache_cst_0/design_4_axcache_cst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_axcache_cst_0 || ORIG_REF_NAME==design_4_axcache_cst_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xbar_0/design_4_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xbar_0 || ORIG_REF_NAME==design_4_xbar_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_interconnect_0_0/design_4_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_axi_interconnect_0_0 || ORIG_REF_NAME==design_4_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axprot_cst_0/design_4_axprot_cst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_axprot_cst_0 || ORIG_REF_NAME==design_4_axprot_cst_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_rst_ps8_1_149M_0/design_4_rst_ps8_1_149M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_rst_ps8_1_149M_0 || ORIG_REF_NAME==design_4_rst_ps8_1_149M_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_zynq_ultra_ps_e_1_0/design_4_zynq_ultra_ps_e_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==design_4_zynq_ultra_ps_e_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_axi_dma_0_1/design_4_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_axi_dma_0_1 || ORIG_REF_NAME==design_4_axi_dma_0_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconstant_0_0/design_4_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xlconstant_0_0 || ORIG_REF_NAME==design_4_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconcat_0_0/design_4_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xlconcat_0_0 || ORIG_REF_NAME==design_4_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xbar_2/design_4_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xbar_2 || ORIG_REF_NAME==design_4_xbar_2} -quiet] -quiet

# IP: bd/design_4/ip/design_4_ps8_1_axi_periph_1/design_4_ps8_1_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_ps8_1_axi_periph_1 || ORIG_REF_NAME==design_4_ps8_1_axi_periph_1} -quiet] -quiet

# IP: bd/design_4/ip/design_4_xlconstant_1_0/design_4_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_xlconstant_1_0 || ORIG_REF_NAME==design_4_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_4/ip/design_4_fir_stream_0_2/design_4_fir_stream_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_fir_stream_0_2 || ORIG_REF_NAME==design_4_fir_stream_0_2} -quiet] -quiet

# IP: bd/design_4/ip/design_4_auto_pc_0/design_4_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_4_auto_pc_0 || ORIG_REF_NAME==design_4_auto_pc_0} -quiet] -quiet

# XDC: h:/UbuntuShared/4601/Vivado/baseDesign_stream/baseline_hls.gen/sources_1/bd/design_4/design_4_ooc.xdc
